language: go
go:
  - "1.15"
services:
  - docker
before_install:
  - export GO111MODULE=on
  - export AWS_ACCESS_KEY_ID=FakeAccessKeyId
  - export AWS_SECRET_ACCESS_KEY=FakeSecretAccessKey
  - export AWS_DEFAULT_REGION=eu-west-1
  - docker run -d -p 9000:8000 amazon/dynamodb-local
  - go get github.com/mattn/goveralls
  - make ensure
script:
  - make continuous-integration
  - go test ./... -tags=integration -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
