AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: A simple micro-service to manage users
Resources:
  UserMicroservice:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: user-microservice
      Timeout: 10
      Events:
        Health:
          Type: Api
          Properties:
            Path: '/health'
            Method: get
        User:
          Type: Api
          Properties:
            Path: '/v1/{proxy+}'
            Method: any
      Environment: 
        Variables:
          GIN_MODE: release
          RUNNING_MODE: lambda

